# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cts
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: services-reader
rules:
  - apiGroups: [""]
    resources: ["endpoints","services","pods"]
    verbs: ["get","watch","list"]
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: read-services
subjects:
  - kind: ServiceAccount
    name: cts
    apiGroup: ""
roleRef:
  kind: Role
  name: services-reader
  apiGroup: rbac.authorization.k8s.io
...
