# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
name: ec-ibmis-lab-ext
description: Egeria lab extension to include IBM Information Server connectors
apiVersion: v1
version: 0.1
icon: https://raw.githubusercontent.com/odpi/egeria/99016e77167fa30dcfade809b061358a92a59973/assets/img/egeria.png
keywords:
  - egeria, open-metadata, connector, lab, ibm, information-server
sources:
  - https://github.com/odpi/egeria-connector-ibm-information-server
home: https://github.com/odpi/egeria-connector-ibm-information-server
maintainers:
  - name: Christopher Grote
    email: chris@thegrotes.net
