# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
service:
  type: NodePort

  nodeport:
    egeria: 30080
    ibmigc: 32446
    ibmigc_kafka: 32092
    igcproxy: 30081

logging:
  level: INFO

imageDefaults:
  registry: docker.io
  namespace: odpi
  tag: latest
  pullPolicy: IfNotPresent

egeria:
  user: myuser
  cohort: coco
  server: myserver

release:
  version: 1.2
  snapshot: true

image:
  egeria:
    name: egeria

  configure:
    name: egeria-configure

# NOTE: this image is "bring your own"...
  ibmigc:
    registry: "localhost:5000"
    namespace: ibm
    name: infosvr
    tag: v11.7.0.2

ibmigc:
  user: isadmin
  password: isadmin
  proxyserver: ibmigc

kafka:
  securityContext:
    enabled: false
  zookeeper:
    persistence:
      enabled: false
  persistence:
    enabled: false

